backend/apps/cart/urls.py
from django.conf.urls import url
from apps.cart.views import CartAddView, CartInfoView, CartUpdataView, CartDeleteView

urlpatterns = [
    # url(r'^register$', views.register, name='register')
    # url(r'^register$', views.register, name='register'),
    url(r'^add$', CartAddView.as_view(), name='add'),
    url(r'^$', CartInfoView.as_view(), name='show'),
    url(r'^update$',CartUpdataView.as_view(), name='update'),
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),
]

backend/apps/goods/urls.py
from django.conf.urls import include, url
from .views import IndexView,DetailView,ListView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
]

backend/apps/user/urls.py
from django.conf.urls import url
from apps.user import views
from apps.user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, UserAddressView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    # url(r'^register$', views.register, name='register')
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(),name='active'),
    # url(r'^register_handle$', views.register_handle, name='register_handle'),  # 注册处理
    url(r'^login$', LoginView.as_view(), name='login'),  # 登录
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 注销
    # url(r'^order$', login_required(UserOrderView.as_view()), name='order'),
    # url(r'^address$',login_required(UserAddressView.as_view()), name='address'),
    #
    # url(r'^$', login_required(UserInfoView.as_view()), name='user'),
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),
    url(r'^address$', UserAddressView.as_view(), name='address'),

    url(r'^$', UserInfoView.as_view(), name='user'),


]

backend/dragonGoods/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

backend/market/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search', include('haystack.urls')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^order/', include('apps.order.urls', namespace='order')),
    url(r'^', include('apps.goods.urls', namespace='goods')),

]

backend/apps/cart/models.py
from django.db import models

# Create your models here.

backend/apps/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import View

from apps.goods.models import GoodsSKU

from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
# Create your views here.


# 前端需要传递的参数: 商品id(sku_id) 商品数量(count)
# 采用ajax post请求
# /cart/add
class CartAddView(View):
    """购物车记录-添加"""
    def post(self, request):
        """添加"""
        # 获取登录用户
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 参数校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 校验商品的数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': '商品数目非法'})

        if count <= 0:
            return JsonResponse({'res': 3, 'errmsg': '商品数目非法'})

        # 业务处理：添加购物车记录
        # cart_2 : {'1':5, '3':2, '4':3}
        # 如果用户的购物车中已经添加过该商品，数目需要累加
        conn = get_redis_connection('default')

        # 拼接key
        cart_key = 'cart_%d'%user.id

        # hget(key, field): 如果field存在，返回field的值，否则返回None
        cart_count = conn.hget(cart_key, sku_id)

        if cart_count:
            # 数目累加
            count += int(cart_count)

        # 判断商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置购物车中商品的数目
        # hset(key, field, value): 如果field存在则更新值，如果不存在则添加新属性
        conn.hset(cart_key, sku_id, count)

        # 获取用户购物车中商品的条目数
        cart_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'cart_count': cart_count, 'message': '添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    """购物车页面显示"""
    def get(self, request):
        """显示"""
        # 获取链接
        conn = get_redis_connection('default')

        # 拼接key
        user = request.user
        cart_key = 'cart_%d'%user.id

        # 从redis中获取用户购物车商品的记录
        # cart_用户id : {'商品id': '商品数量'}
        # hgetall(key): 返回一个字典: {'商品id': '商品数量'}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_count = 0
        total_amount = 0
        # 获取对应商品的信息
        for sku_id, count in cart_dict.items():
            # 根据sku_id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)

            # 计算商品的小计
            amount = sku.price*int(count)

            # 给sku对象增加属性amount和count
            # 分别保存用户购物车中添加商品的小计和商品的数目
            sku.amount = amount
            sku.count = int(count)

            # 追加商品
            skus.append(sku)

            # 累加计算用户购物车中商品的总件数和总价格
            total_count += int(count)
            total_amount += amount

        # 组织上下文
        context = {'skus': skus,
                   'total_count': total_count,
                   'total_amount': total_amount}

        # 使用模板
        return render(request, 'market/cart.html', context)



# 前段传递的参数： 商品id 更新数量（count)
# 采用ajax post 请求
# /cart/update

class CartUpdataView(View):
    """购物车记录更新"""
    def post(self,request):
        """更新"""
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0, 'errmsg':'用户未登录'})
        # 接受参数
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 校验参数
        if not all ([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验商品id
        try:
            sku = GoodsSKU.objects.get(id = sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})
        # 校验商品的数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': '商品数目非法'})
        if count <= 0:
            return JsonResponse({'res': 3, 'errmsg': '商品数目非法'})

        # 业务处理
        conn = get_redis_connection('default')
        # 拼接key
        cart_key = 'cart_%d'%user.id
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 更新redis中商品的数目
        #hset(key field value)
        conn.hset(cart_key, sku_id, count)
        print(conn.hget(cart_key,sku_id))
        #
        return JsonResponse({'res':5, 'message':'更新成功'})



class CartDeleteView(View):
    def post(self,request):
        """删除"""
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg':'用户未登录'})
        # 接受参数
        sku_id = request.POST.get('sku_id')
        # count = request.POST.get('count')
        print(sku_id)
        # print(count)
        # 校验参数
        # if not all([sku_id, count]):
        if not all([sku_id]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验商品id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        conn.hdel(cart_key,sku_id)



        cart_vals = conn.hvals(cart_key)
        cart_count = 0
        for val in cart_vals:
            cart_count += int(val)

        return JsonResponse({'res': 3, 'cart_count':cart_count, 'message': '删除成功'})

backend/templates/market/base.html
{# 注册 登录 首页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static from staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
                    <span>|</span>
					<a href="{% url 'goods:index' %}">首页</a>
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

backend/templates/market/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'market/base.html' %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

backend/templates/market/base_no_cart.html
{# 购物车 提交订单 #}
{% extends 'market/base.html' %}
{% load static from staticfiles %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

backend/templates/market/base_user_center.html
{# 用户中心3页面 #}
{% extends 'market/base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{# 网页主体内容块 #}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心-右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

backend/templates/market/index.html
{#{% extends 'market/base.html' %}#}
{#{% load static from staticfiles %}#}
{#{% block title %}天天生鲜-首页{% endblock title %}#}
{#{% block topfiles %}#}
{#    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>#}
{#{% endblock topfiles %}#}
{#{% block body %}#}
{#	<div class="header_con">#}
{#		<div class="header">#}
{#			<div class="welcome fl">欢迎来到天天生鲜!</div>#}
{#			<div class="fr">#}
{#                {% if user.is_authenticated %}#}
{#				<div class="login_btn fl">#}
{#					欢迎您：<em>{{ user.username }}</em>#}
{#                    <span>|</span>#}
{#					<a href="{% url 'user:logout' %}">退出</a>#}
{#				</div>#}
{#                {% else %}#}
{#				<div class="login_btn fl">#}
{#					<a href="{% url 'user:login' %}">登录</a>#}
{#					<span>|</span>#}
{#					<a href="{% url 'user:register' %}">注册</a>#}
{#				</div>#}
{#                {% endif %}#}
{#				<div class="login_info fl">#}
{#					欢迎您：<em>张 山</em>#}
{#				</div>#}
{#				<div class="login_btn fl">#}
{#					<a href="login.html">登录</a>#}
{#					<span>|</span>#}
{#					<a href="register.html">注册</a>#}
{#				</div>#}
{#				<div class="user_link fl">#}
{#					<span>|</span>#}
{#					<a href="user_center_info.html">用户中心</a>#}
{#					<span>|</span>#}
{#					<a href="cart.html">我的购物车</a>#}
{#					<span>|</span>#}
{#					<a href="user_center_order.html">我的订单</a>#}
{#				</div>#}
{#			</div>#}
{#		</div>		#}
{#	</div>#}
{##}
{#	<div class="search_bar clearfix">#}
{#		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>#}
{#		<div class="search_con fl">#}
{#			<input type="text" class="input_text fl" name="" placeholder="搜索商品">#}
{#			<input type="button" class="input_btn fr" name="" value="搜索">#}
{#		</div>#}
{#		<div class="guest_cart fr">#}
{#			<a href="#" class="cart_name fl">我的购物车</a>#}
{#			<div class="goods_count fl" id="show_count">1</div>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="navbar_con">#}
{#		<div class="navbar">#}
{#			<h1 class="fl">全部商品分类</h1>#}
{#			<ul class="navlist fl">#}
{#				<li><a href="">首页</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">手机生鲜</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">抽奖</a></li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="center_con clearfix">#}
{#		<ul class="subnav fl">#}
{#          商品种类信息  #}
{#            {% for type in types %}#}
{#			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>#}
{#		    {% endfor %}#}
{#        </ul>#}
{#		<div class="slide fl">#}
{#			<ul class="slide_pics">#}
                {#页轮播商品信息#}
{#                {% for banner in index_banner %}#}
{#                    <li><a href="#"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>#}
{#                {% endfor %}#}
{#			</ul>#}
{#			<div class="prev"></div>#}
{#			<div class="next"></div>#}
{#			<ul class="points"></ul>#}
{#		</div>#}
{#		<div class="adv fl">#}
{#            商品促销信息#}
{#            {% for promotion in promotion_banner %}#}
{#			<a href="{{ promotion.url }}"><img src="{{ promotion.image.url }}"></a>#}
{#            {% endfor %}#}
{#            {% for banner in promotion_banner %}#}
{#			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>#}
{#            {% endfor %}#}
{##}
{#		</div>#}
{#	</div>#}
{# {% for type in types %}#}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
                {# 展示type种类的首页展示的文字商品的信息 #}
{#                {% for banner in type.title_banner %}#}
{#				<a href="#">{{ banner.sku.name }}</a>#}
{#				{% endfor %}#}
{#			</div>#}
{#			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>#}
{#			<ul class="goods_list fl">#}
                {# 展示type种类首页展示的图片商品的信息 #}
{#                {% for banner in type.image_banner %}#}
{#				<li>#}
{#					<h4><a href="#">{{ banner.sku.name }}</a></h4>#}
{#					<a href="#"><img src="{{ banner.sku.image.url }}"></a>#}
{#					<div class="prize">¥ {{ banner.sku.price }}</div>#}
{#				</li>#}
{#                {% endfor %}#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{#    {% endfor %}#}
{#{% endblock body %}#}
{#{% block bottomfiles %}#}
{#	<script type="text/javascript" src="js/slideshow.js"></script>#}
{#	<script type="text/javascript">#}
{#		BCSlideshow('focuspic');#}
{#		var oFruit = document.getElementById('fruit_more');#}
{#		var oShownum = document.getElementById('show_count');#}
{##}
{#		var hasorder = localStorage.getItem('order_finish');#}
{##}
{#		if(hasorder)#}
{#		{#}
{#			oShownum.innerHTML = '2';#}
{#		}#}
{##}
{#		oFruit.onclick = function(){#}
{#			window.location.href = 'list.html';#}
{#		}#}
{#	</script>#}
{#{% endblock bottomfiles %}#}



{% extends 'market/base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {# 展示商品种类的信息 #}
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {# 展示首页轮播商品的信息 #}
                {% for banner in index_banner %}
				<li><a href="#model0{{ forloop.counter }}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {# 展示首页促销活动信息 #}
            {% for banner in promotion_banner %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {# 展示type种类的首页展示的文字商品的信息 #}
                {% for banner in type.title_banner %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {# 展示type种类首页展示的图片商品的信息 #}
                {% for banner in type.image_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}
                                                                                                                                                                                                                                                                                                                            {#{% block bottomfiles %}#}
{#	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>#}
{#	<script type="text/javascript">#}
{#		BCSlideshow('focuspic');#}
{#		var oFruit = document.getElementById('fruit_more');#}
{#		var oShownum = document.getElementById('show_count');#}
{##}
{#		var hasorder = localStorage.getItem('order_finish');#}
{##}
{#		if(hasorder)#}
{#		{#}
{#			oShownum.innerHTML = '2';#}
{#		}#}
{##}
{#		oFruit.onclick = function(){#}
{#			window.location.href = 'list.html';#}
{#		}#}
{#	</script>#}
{#{% endblock bottomfiles %}#}

backend/templates/market/static_base.html
{# 注册 登录 首页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static from staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>